import fs from "fs"
import path from "path"
import { sync as globSync } from "glob"

import { validateQuestionFile } from "./validate"
import type { Question } from "../src/types/index"

interface CategoryEntry {
  slug: string
  displayName: string
  description: string
  topics: {
    slug: string
    categorySlug: string
    fullSlug: string
    questionCount: number
  }[]
}

function main() {
  const dataDir = path.resolve(process.cwd(), "data/categories")
  const outPath = path.resolve(process.cwd(), "src/generated/index.ts")

  if (!fs.existsSync(dataDir)) {
    console.log("No data/categories directory found — writing empty index.")
    fs.mkdirSync(path.dirname(outPath), { recursive: true })
    fs.writeFileSync(
      outPath,
      `// AUTO-GENERATED by scripts/build-index.ts — DO NOT EDIT MANUALLY\nimport type { CategoryIndex, Question } from "../types"\nexport const CATEGORIES: Record<string, CategoryIndex> = {} as const\nexport const TOPIC_MAP: Record<string, Question[]> = {} as const\n`,
      "utf-8"
    )
    console.log("Empty index written.")
    return
  }

  const categoryDirs = fs
    .readdirSync(dataDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort()

  const categories: Record<string, CategoryEntry> = {}
  const topicMap: Record<string, Question[]> = {}
  const seenIds = new Set<string>()

  for (const categorySlug of categoryDirs) {
    const categoryDir = path.join(dataDir, categorySlug)
    const metaPath = path.join(categoryDir, "_meta.json")

    if (!fs.existsSync(metaPath)) {
      console.error(`ERROR: Missing _meta.json in ${categorySlug}/`)
      process.exit(1)
    }

    const meta = JSON.parse(fs.readFileSync(metaPath, "utf-8"))
    if (!meta.displayName || !meta.description) {
      console.error(`ERROR: _meta.json in ${categorySlug}/ must have displayName and description`)
      process.exit(1)
    }

    categories[categorySlug] = {
      slug: categorySlug,
      displayName: meta.displayName,
      description: meta.description,
      topics: [],
    }

    const topicFiles = globSync("*.json", { cwd: categoryDir }).filter((f) => f !== "_meta.json").sort()

    for (const topicFile of topicFiles) {
      const topicSlug = topicFile.replace(".json", "")
      const fullPath = path.join(categoryDir, topicFile)
      const raw = fs.readFileSync(fullPath, "utf-8")
      const data = JSON.parse(raw)

      validateQuestionFile(data, `${categorySlug}/${topicFile}`, seenIds)

      const fullSlug = `${categorySlug}/${topicSlug}`
      topicMap[fullSlug] = data.questions
      categories[categorySlug].topics.push({
        slug: topicSlug,
        categorySlug,
        fullSlug,
        questionCount: data.questions.length,
      })

      console.log(`  OK  ${fullSlug} (${data.questions.length} questions)`)
    }
  }

  const output = `// AUTO-GENERATED by scripts/build-index.ts — DO NOT EDIT MANUALLY
// Re-generated on every build.

import type { CategoryIndex, Question } from "../types"

export const CATEGORIES: Record<string, CategoryIndex> = ${JSON.stringify(categories, null, 2)} as const

export const TOPIC_MAP: Record<string, Question[]> = ${JSON.stringify(topicMap, null, 2)} as const
`

  fs.mkdirSync(path.dirname(outPath), { recursive: true })
  fs.writeFileSync(outPath, output, "utf-8")
  console.log(`\nIndex written to src/generated/index.ts`)
  console.log(`${Object.keys(categories).length} categories, ${Object.keys(topicMap).length} topics indexed.`)
}

main()
